### ISSUE TITLE
Building insctructions

### ISSUE THREAD

**Issue by enolp** [Bleuzen/Blizcord#15]
I would like to build my custom version of Blizcord only for testing proposes but I cannot find any information to do that

**Comment by Bleuzen** [comment]
Hi, this is how I build the .exe file:
you need a linux system with these tools installed:
 - maven
 - ant
 - proguard
 - launch4j

Depending on which distribution you are using and where you installed the tools, you may have to change the path to proguard and launch4j in the file `build.xml`.

Then just execute the `build.sh` script as any other shell / bash script and you got the build.
