### ISSUE TITLE
Issue to listen Youtube video 

### ISSUE THREAD

**Issue by Anthyx17** [Bleuzen/Blizcord#20]
Hello !

Thank you for your awesome work. Listen local files on Discord is perfect and very simple! 
But I have a problem to listen youtube video. I share you screenshot in attach files
![Capture](https://user-images.githubusercontent.com/64550830/80628220-4ef6c280-8a51-11ea-8833-47fee0a41daf.PNG)

I hope you will answer.

Best regards

**Comment by Anthyx17** [comment]
Sorry this screenshot isn't the good one. It's from the 9.6 version. Here is the screenshot of the 10.0 version. 
![Capture](https://user-images.githubusercontent.com/64550830/80628832-3fc44480-8a52-11ea-8641-63452aaeb6d0.PNG)

And sorry for my bad english I hope you will understand me !

**Comment by Bleuzen** [comment]
Hi, please try the new version 0.10.1:
https://github.com/Bleuzen/Blizcord/releases/download/v0.10.1/Blizcord.exe

**Comment by Anthyx17** [comment]
I try it but now it doesn't work anymore ^^'

**Comment by Anthyx17** [comment]
Listen local file doesn't work too with the new version

**Comment by Bleuzen** [comment]
Both work fine on my machine with v0.10.1. I tested the video you had problems with and a local file.

Any error message on your side?

**Comment by Anthyx17** [comment]
No ! There isn't error message. When I put -play or -search the music is never played. It stays at 0 second

**Comment by Bleuzen** [comment]
I re-released 0.10.1. Please try redownloading the .exe file and try again:
https://github.com/Bleuzen/Blizcord/releases/download/v0.10.1/Blizcord.exe

**Comment by Anthyx17** [comment]
Thanks for tour help ! It works perfectly now !
