### ISSUE TITLE
Bot commands

### ISSUE THREAD

**Issue by FredrikSB** [Bleuzen/Blizcord#26]
Not all of the listed commands work.
![image](https://user-images.githubusercontent.com/75475988/101149682-91076880-361f-11eb-9756-ffc1090bb612.png)
I am not able to play local files through the bot.

**Comment by Bleuzen** [comment]
Hi, as seen in the screenshot, this is not how to use the play command.
For example with default prefix it is:

`!play <path to a audio file on your computer>`

As it says it plays LOCAL files, so files stored on your computer. You can not upload a file to Discord, the bot won't play it this way.
