### ISSUE TITLE
How do I play a local file?

### ISSUE THREAD

**Issue by TR27XD** [Bleuzen/Blizcord#27]
I added a playlist with !add and the file path of the folder. The bot started playing music as it joined, the first one on the folder. Now if I want it to play a specific file on the folder, what exactly should I put after the !play command?
And is it possible to get a "Now Playing «song name»" message, every time the song changes?

**Comment by Bleuzen** [comment]
To play a local file is as simple as adding the filename at the end of the path.

```
!play /home/user/music/some_artist/album/some_song.mp3
```

The bot already displays the currently playing song as the current playing game.
