### ISSUE TITLE
!search don't add a video in the playlist

### ISSUE THREAD

**Issue by llijaz** [Bleuzen/Blizcord#5]
please make something like an argument for !search, for adding in the result into the current playlist!
thanks :)

**Comment by Bleuzen** [comment]
I like it how simple it is currently.
Just type
`!search _keyword_`
I don't want to add more arguments to it.

Would it be ok for you, if I change the search result from play direct to add to the playlist?
So the command would still be the same, but the search result will get added to the playlist and not starts playing directly.

**Comment by llijaz** [comment]
that would be fine. thanks :)

**Comment by Bleuzen** [comment]
I changed it in 0.7.1.
