### ISSUE TITLE
Can't start bot (Error 0?)

### ISSUE THREAD

**Issue by CreamedRicePudding** [Bleuzen/Blizcord#6]
![blizcord](https://user-images.githubusercontent.com/41242381/42737600-0708033a-886e-11e8-8583-7c1da2246829.PNG)

The bot started and crashed the first time to create the config/control channel etc but I've never been able to keep it open. It just crashes with an error popup with text "0".

**Comment by Bleuzen** [comment]
Hi. Sorry, usually it should display a more useful error message. But we will try to get some more information.

Please start Blizcord within a Command Prompt.
cd to the directory of your Blizcord exe file and type:
`java -jar Blizcord-0.8.10.exe --debug --gui`
and post the output here (or better on https://hastebin.com/)

**Comment by CreamedRicePudding** [comment]
Haven't checked in for a while sorry. I updated to 0.8.11 and am still getting the same issue

Here is the GUI output:
https://hastebin.com/gojuxewuho.makefile

And without GUI:
https://hastebin.com/huvuwumogo.makefile

**Comment by Bleuzen** [comment]
Which Java version are you using? This is made for Java 8, there could be problems with other versions.

Also have you tryed to (re)move your config file? Maybe there is something wrong with your config.

If you still have this problem, I have no idea currently. We could meet on Discord / TeamViewer and then I could try something.. but until now I have no idea how to fix it to be frank, never saw that error before.

**Comment by CreamedRicePudding** [comment]
Using Java version 8 update 181

Just deleted the config and made a new one via the Edit button. This was fine and it made the default config but when I click edit again and customise the values, clicking the apply button doesn't actually save changes - The button fades and I can't click it after the first time.

This has happened every time I've made the config, even on the older version but I'd forgotten about it until now. I'm still able to go and manually edit the config though so I'm not sure if it's a related issue.

Here's my config anyway (or one of my attempts at least)
https://hastebin.com/kigosedeva.json

I've replaced the bot token with "mytoken" and I've tried with a botadmin role and leaving the default.

**Comment by Bleuzen** [comment]
Ah I found the problem. The "#" starts a comment in the config file, so "#" and everything behind is not valid as value.
You can't use "#" as command prefix. (I should implement a warning message in the next version.)

**Comment by Bleuzen** [comment]
New version 0.8.12 should now display a warning message instead of freezing the Apply button when saving the config.
Also it doesn't crash anymore when the value is invalid. It just replaces it with nothing and displays a debug message.

I think this is better now. Happy testing :)

**Comment by CreamedRicePudding** [comment]
That's fixed everything man thanks :)
