### ISSUE TITLE
Automatic shuffle when loading a playlist

### ISSUE THREAD

**Issue by enolp** [Bleuzen/Blizcord#7]
I don't know if there is a trick to do it but it would be nice if there is an option to automaticaly shuffle everytime lists that you are going to play. Loading a list and typing --shuffle everytime is annoying

**Comment by Bleuzen** [comment]
It is not yet possible, but I can add an option for that.
Would be a "Auto-Shuffle playlists" checkbox be ok for you? It would turn shuffle on always when a playlist is loaded, every playlist. This would be easy to implement.

Or do you need an option to save it in the playlist itself, if it will be shuffled or not? (This would take a bit longer and destroy the current playlist format.)

**Comment by enolp** [comment]
That's I was thinking about, the current method loads the playlists but you have to listen always to the first song in that lists before --shuffle option gets loaded

**Comment by Bleuzen** [comment]
Next version will contain the new `!loadshuffle` command ;)
https://github.com/Bleuzen/Blizcord/commit/b6637a5a0d188cc5b2e179413469c5a14976153d

You won't have to listen to the first song, since it is shuffled before playing starts.

**Comment by enolp** [comment]
Woah!! That was quick. Thanks for the great work

**Comment by Bleuzen** [comment]
@enolp Version 0.9.0 just got released
