### ISSUE TITLE
Show only the filename instead of the full path

### ISSUE THREAD

**Issue by enolp** [Bleuzen/Blizcord#9]
Showing only the filename (without extension) on the bot's "Playing" status instead of the full path would be a nice feature

**Comment by Bleuzen** [comment]
Filename would be ok. I can remove the path.

But I would leave the file extension, because I like to know if a local file is playing. With a file extension it is easier to see that it is a local file playing and track name is not read from track tags.

I would remove path but keep filename + extension in next version. I think this is best for most users.
What do you think?

**Comment by enolp** [comment]
I would make a checkbox option to whether show file extensions. IMHO, I think most users does not care about the file type or if it is played from a local or remote path. Also, If file has ID3 info on it, make Blizcord able to read it

**Comment by Bleuzen** [comment]
In my opinion it is always a nice info if it gets streamed or played from local file. If file is streamed it could explains lags etc..

To make a new checkbox just for such a little change would be overkill I think.

I will let it display the filename for now and will look into reading from tags when I have some time for that.
In the future if the file has tags, it will display song name from there, and if it has no tags, it will display file name.

To display if the source is a local file.. well I will see if I can find a nice looking solution somewhen.

**Comment by enolp** [comment]
To show if a file is remote or local you could add somethinng like [REMOTE] or [LOCAL] after the song's name

**Comment by Bleuzen** [comment]
@enolp Please test:
https://github.com/Bleuzen/Blizcord/releases/tag/0.9.3

**Comment by enolp** [comment]
Now I get this error starting JDA
`#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f5a14aa7e24, pid=31410, tid=0x00007f5a2d619700
#
# JRE version: OpenJDK Runtime Environment (8.0_192-b26) (build 1.8.0_192-b26)
# Java VM: OpenJDK 64-Bit Server VM (25.192-b26 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libX11.so.6+0x90e24]  XkbGetUpdatedMap+0x4
#
# Core dump written. Default location: /home/antr-asus/core or core.31410
#
# An error report file with more information is saved as:
# /home/antr-asus/hs_err_pid31410.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#`

Which is very strange because I can run the previous version without problems. I'm using Arch Linux

**Comment by enolp** [comment]
I'm using AUR package but I had to overwrite manually Blizcord.exe because I'm unable to update it due to checksum issue

**Comment by Bleuzen** [comment]
To overwrite or replace a file should not be needed.
Try to clear your package cache and build again.

**Comment by enolp** [comment]
Ok, my bad. I was running Blizcord over ssh and some does not work there, I run it on graphical mode and now it works.

File extension are not shown when a file has tags, (this file it's .m4a):

![screenshot_20181103_204150](https://user-images.githubusercontent.com/16736782/47956704-a91fe000-dfa0-11e8-9ad8-8972f8aba1e6.png)

If file contains no tags, Blizcord shows the filename with extension:

![screenshot_20181103_204721](https://user-images.githubusercontent.com/16736782/47956737-54c93000-dfa1-11e8-830c-f209caa96bd6.png)

Right now I cannot test .ogg files with tags because I don't have any

**Comment by Bleuzen** [comment]
I don't see a reason why it should not work over ssh. (Maybe JNativeHook makes problems, try to disable the media keys in the config file.)

Yes this is correct. Currently it displays the artist and songs title if the audio file has tags.
It displays filename if there are no tags.
This is how I did it in this version.

To test with ogg, you can tag one yourself. There is a nice program in the arch repos that I can recommend:
`sudo pacman -S kid3`
It has a GUI and CL version and you can tag most formats pretty easy.

**Comment by Bleuzen** [comment]
You are right, we found another bug in lavaplayer. Hell I love and hate this.
https://github.com/sedmelluq/lavaplayer/issues/141

Will have to wait until he fixed it.

Well, at least mp3 files do work. (But who still uses mp3?)
And opus works, if you can live with some "=".

**Comment by enolp** [comment]
.m4a file tags works fine too. I can wait until lavaplater fixes opus file tags. Thanks for your quick work and fast response, amazing!!!
